### ISSUE TITLE
Add a tooltip component

### ISSUE THREAD

**Issue by chowington** [VEuPathDB/CoreUI#100]
Currently we use at least three different methods of displaying tooltips. The most notable is our [custom wrapper component](https://github.com/VEuPathDB/web-components/blob/49c33c702fe0a0f0a9d3283d016565f453c6cb72/src/components/widgets/Tooltip.tsx) around MUI's Tooltip component that we have in web-components. We may want to emulate that design here and make this our primary source of a Tooltip component, or we may want to redesign it.

**Comment by asizemore** [comment]
See also #75
