### ISSUE TITLE
Update Switch component

### ISSUE THREAD

**Issue by chowington** [VEuPathDB/CoreUI#104]
Following the styling meeting documented [here](https://veupathdb.atlassian.net/wiki/spaces/WG/pages/52658256/EDA+Styling+Meeting+August+17+2022), make the following changes to the Switch component:

- [x] Change name to Toggle
- [x] Make toggle body be pill-shaped (knob stays a circle)
- [x] Remove color variants (filled, floating, outline)
- [x] Add small version
- [x] State colors: 
- Off, default (no hover): Outlined theme color
- Off, hover: Light theme color fill
- On, default: Filled theme color
- On, hover: Darker filled theme color
- Off and disabled: Grey outline
- On and disabled: Grey fill

**Comment by SheenaTomko** [comment]
Looks great! Replaced in drop down menus, below stratification variables, and in plot parameters below plots
