### ISSUE TITLE
Make Select and Button same height

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/CoreUI#132]
Opening for discussion.

In the screenshot below we can see the "medium" size Button is a little larger than the Select components in its row. Since we mostly use the "medium" size button, should we make the Select components the same height?

<img width="1127" alt="Screen Shot 2022-12-09 at 3 03 53 PM" src="https://user-images.githubusercontent.com/11710234/206787205-086ebe47-9847-458a-9e3a-4666f0ff4e61.png">

**Comment by dmfalke** [comment]
I agree with this. Perhaps the Select components should use the Button component?

**Comment by asizemore** [comment]
That sounds ideal. I think the current Button only allows icons on the left. But perhaps SwissArmyButton could be updated so that it supports icons on both sides, and Buttons will always have it on the left but Selects will always have it on the right?

**Comment by dmfalke** [comment]
That sounds reasonable to me!

**Comment by asizemore** [comment]
@asizemore double check this is still an issue

**Comment by asizemore** [comment]
seen on feature mbio today. still an issue
