### ISSUE TITLE
compute app: first option should not be blue until moused-over

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/CoreUI#145]
In the new compute app flow for ranked abundance, I need to first select the data. I wanted to select "Phylum" and when i opened the dropdown Phylum was in blue (making it seem like I had selected it). I was confused as to why the dropdown still said "Select the data"

Please don't highlight the 1st option in the dropdown before the user clicks on anything (in my example, Phylum should have a white background and look identical to the other possible options). Only once the user mouses over that option should Phylum (or other selection) turn blue.

The same feedback is true for "Method" and likely also true in other types of compute apps (i only looked at ranked abundance)

<img width="805" alt="image" src="https://user-images.githubusercontent.com/25450900/216723970-97ec4acc-873e-4cd7-a337-42527900047c.png">

**Comment by jernestmyers** [comment]
Closed by https://github.com/VEuPathDB/web-monorepo/pull/21

**Comment by danicahelb** [comment]
this looks so much better now, thanks @jernestmyers!



![Image](https://user-images.githubusercontent.com/25450900/231895855-2aaa1d7c-09c9-417d-9e6e-d2eb414b2881.png)
