### ISSUE TITLE
Add `cursor: pointer` to icon used to collapse/expand banners

### ISSUE THREAD

**Issue by jernestmyers** [VEuPathDB/CoreUI#148]
> Also, I think we should open a follow-up ticket in `CoreUI` to change the cursor of the `collapsibleIcon` to be `pointer`, which would better indicate that it's a clickable button.
> 
> [Here's the relevant code](https://github.com/VEuPathDB/CoreUI/blob/e9686d345ec809e74843e65be91491bc9fe3b55e/src/components/banners/Banner.tsx#L240-L255) in the `Banner` component.

Definitely I like the idea @jernestmyers: I was thinking the case before but didn't have time to do that. Perhaps you can easily handle it at a follow-up ticket in the near future 😄

_Originally posted by @moontrip in https://github.com/VEuPathDB/web-eda/issues/1636#issuecomment-1440638480_

**Comment by dmfalke** [comment]
I think that if an icon is clickable, we should wrap it in a `<button>` and not an `<a>`, for accessibility.
