### ISSUE TITLE
Request: Select component

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/CoreUI#26]
In https://github.com/VEuPathDB/web-eda/pull/811 I have used the Material UI Select component, but I guess we would like our own consistent Input.

The MUI inputs are poorly executed...
![image](https://user-images.githubusercontent.com/308639/151636909-7bd2daf4-e31f-48fb-b6a0-56e326a01308.png)

Ideally we'd want to be consistent with the `VariableTreeDropdown` component as shown here:
![image](https://user-images.githubusercontent.com/308639/151636847-a0b33284-d426-4e4c-90c4-bf5f96d958c6.png)

**Comment by asizemore** [comment]
@bobular to clarify, do you think we should make a CoreUI version of a selector button that would a) be a CoreUI version of `VariableTreeDropdown` and b) be used in the map as well as vizs? Or would it be better to make a CoreUI select component that is visually consistent with `VariableTreeDropdown`?

**Comment by asizemore** [comment]
@bobular do the new `SelectList`, `SelectTree`, or `SingleSelect` cover your use case?

**Comment by bobular** [comment]
Nice archaeological find, @asizemore!  Yes, the `SingleSelect` looks most useful for the entity picker we will need in the map. Thanks.

**Comment by asizemore** [comment]
Excellent! Glad it will work! Closing issue
