### ISSUE TITLE
Consolidate tooltip components

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/CoreUI#75]
We can start with moving [this component](https://github.com/VEuPathDB/web-components/blob/main/src/components/widgets/Tooltip.tsx) to this repo.

A related follow-up task will be to convert all existing tooltips to use this one.

@jernestmyers suggests moving to a newer MUI version - might be better placement mechanism

**Comment by asizemore** [comment]
See also https://github.com/VEuPathDB/CoreUI/issues/100

**Comment by dmfalke** [comment]
Note that this issue includes a reference to improving the performance of tooltips when we have a large list of elements with tooltips: https://github.com/VEuPathDB/CoreUI/issues/127#issue-1448643753

ETA I'm not suggesting that we address this at the same time as consolidation. I just want to keep the idea in our heads.
